services:
  server:
    build:
      dockerfile: Dockerfile
    image: github.com/moozeq/openedai-speech
    environment:
      - TTS_HOME=voices
      - HF_HOME=voices
      - PRELOAD_MODEL=halo
      - COQUI_TOS_AGREED=1
    ports:
      - "8880:8880"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    restart: unless-stopped
