services:
  server:
    build:
      dockerfile: Dockerfile
    image: github.com/moozeq/openedai-speech
    env_file: speech.env
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    restart: unless-stopped
